name: Sync Fork
on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:

  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git remote add fork https://github.com/TiagoVenceslau/TiagoVenceslau.git
          git fetch --prune --unshallow
          git pull fork main --alow-unrelated-histories
          git push origin main --force-with-lease
